class UserAlreadyExistsError(Exception):
    pass

class UserNotFoundError(Exception):
    pass
